<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VisionUserID</name>
   <tag></tag>
   <elementGuidId>575c2c75-7b89-4a4a-8662-be6428acc285</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='combined-login']//input[@name='logon']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name=\'logon\']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='combined-login']//input[@name='logon']</value>
   </webElementProperties>
</WebElementEntity>
