<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elFirstDocLink</name>
   <tag></tag>
   <elementGuidId>f5c4f1ce-ae3f-4255-8aca-98d48fa02ec8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@id='fund-documents']//tr/td[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id='fund-documents']//tr/td[3]/a</value>
   </webElementProperties>
</WebElementEntity>
