<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elFirstFundLink</name>
   <tag></tag>
   <elementGuidId>7b25fb83-9c26-457b-8324-ffd61de7c589</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@id='fund-documents']//tr/td[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id='fund-documents']//tr/td[1]/a</value>
   </webElementProperties>
</WebElementEntity>
