<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tblProspectFundTable</name>
   <tag></tag>
   <elementGuidId>fc33a70e-8d8d-4924-a6cb-e17333606bce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@id='fund-documents']//tr//td[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id='fund-documents']//tr//td[1]/a</value>
   </webElementProperties>
</WebElementEntity>
