<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AccountDropDown</name>
   <tag></tag>
   <elementGuidId>2a92bfb1-0b2c-4f23-8685-9e1d31f5b810</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;client-accounts-dropdown&quot;]/li/a[1]/span/parent::a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;client-accounts-dropdown&quot;]/li/a[1]/span/parent::a</value>
   </webElementProperties>
</WebElementEntity>
