<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PerspectiveBlog_FirstBlogHeadding</name>
   <tag></tag>
   <elementGuidId>dd513e53-e5aa-4cc3-abe7-1dca1a34f511</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@id='highlight-row']//a[text()])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@id='highlight-row']//a[text()])[1]</value>
   </webElementProperties>
</WebElementEntity>
