<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AccountSummary</name>
   <tag></tag>
   <elementGuidId>df02b535-443c-4abc-a347-96aeb4cf26a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;MUTUAL_FUNDS-container&quot;]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;MUTUAL_FUNDS-container&quot;]/div</value>
   </webElementProperties>
</WebElementEntity>
