<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elClientName1</name>
   <tag></tag>
   <elementGuidId>52c08bf9-fc81-41d8-b27c-7d5d7f692256</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;MUTUAL_FUNDS-container&quot;]/div[1]/div[1]/p[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;MUTUAL_FUNDS-container&quot;]/div[1]/div[1]/p[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
