<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elcompleteStatment</name>
   <tag></tag>
   <elementGuidId>bceaa2e2-3ba0-4e39-94fd-d0cb7133ba74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='handleCompleteDailyStmt']/img/parent::a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='handleCompleteDailyStmt']/img/parent::a</value>
   </webElementProperties>
</WebElementEntity>
