<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elShowAccounts</name>
   <tag></tag>
   <elementGuidId>d140fd5a-1458-4a2d-827d-2fb282798299</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='MUTUAL_FUNDS']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='MUTUAL_FUNDS']/div/p</value>
   </webElementProperties>
</WebElementEntity>
