<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSaveChanges</name>
   <tag></tag>
   <elementGuidId>dd3fda0d-9f5b-4d1b-9ec6-b6bc134bb136</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id=&quot;submit-balance-alerts&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id=&quot;submit-balance-alerts&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id=&quot;submit-balance-alerts&quot;]</value>
   </webElementProperties>
</WebElementEntity>
