<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chkBoxAddressChange</name>
   <tag></tag>
   <elementGuidId>c6cd35f2-1a31-43e6-af15-6c7540f63604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name='form:regList:0:selboolean4']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@name='form:regList:0:selboolean4']</value>
   </webElementXpaths>
</WebElementEntity>
