<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkFund_ExchangesPage</name>
   <tag></tag>
   <elementGuidId>be4f1db4-8292-43b7-a3bc-30d32d88f56e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class='charttext']//a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//*[@class='charttext']//a)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@class='charttext']//a)[1]</value>
   </webElementProperties>
</WebElementEntity>
